### ISSUE TITLE
Moving cards within full buckets should nudge instead of swapping

### ISSUE THREAD

**Issue by liamwooding** [tableflip/posc#11]
- Fill a bucket
- Drag a card from this bucket to a slot in the same bucket at least 2 slots away
- The 2 cards swap places, leaving all other cards in place

I feel that the proper behaviour here is:
- Card in destination slot & and all cards in between are nudged towards origin slot
- Card in origin slot moves to destination slot

**Comment by olizilla** [comment]
Superseded by https://github.com/tableflip/posc/issues/13

**Comment by pgreenwo** [comment]
I agree
