### ISSUE TITLE
When dragging cards, slots don't always detect hover correctly

### ISSUE THREAD

**Issue by liamwooding** [tableflip/posc#12]
- Put 3 cards in a row in bucket
- Pick up 1st card
- Drag & hover over 2nd slot, card in 2nd slot shifts right to indicate hover
- Continue dragging & hover over 3rd slot
- 2nd slot continues to think it's being hovered over

**Comment by olizilla** [comment]
Implementation and visualisation of drop has changed, so this bug is no longer present.
