### ISSUE TITLE
Card alignment

### ISSUE THREAD

**Issue by pgreenwo** [tableflip/posc#13]
The cards should right-align in the priority rows.  

## Background 

As a communication device, the POSC tool is intended to answer the question: "What should I do next?" for members of a large self-organising team or entity (>100 people).  The board is intended to show priority on the left axis (top priority at the top), and sequence on the bottom axis (using the western standard of left as next and right as last). 

So that the top priority objective is at the top right, and its pre-requisite objectives are to its left.  (The key insight is that a pre-requisite to the top right objective is also a top priority.)

## Implications

This has a number of implications:

1) Any new card should be created in the right-most available space in it's priority line.
2) There should be no gaps between cards.
3) For the trash area, this logic is destroyed as there is no priority or sequence, so left alignment seems a smart choice in this area.  The card behaviour in [JQuery Gridly] (http://ksylvest.github.io/jquery-gridly/) would work for the trash area.
4) When you reduce the width of the browser, the priority sequence breaks onto two lines.  This shouldn't be allowed for the priority lines (don't care about the trash area, but naturally the width will be defined by the priority lines if we keep it below the POSC board.).

You can see this functionality on the [prototype] (http://jsfiddle.net/pgreenwo/bJE4k/show/).  The main issue with the interface behaviour of the prototype is that you can over-fill the priority lines.

**Comment by olizilla** [comment]
As per: https://github.com/tableflip/posc/issues/13#issuecomment-67741176
the required behaviour when moving a card:

```js
if row is full?
   // Deny
else
   // Move existing cards left until the slot is free, and allow the move.
```

We'll add visual cues when the move is denied, otherwise the user may assume an error occurred if there action is ignored.

**Comment by pgreenwo** [comment]
Yes

**Comment by olizilla** [comment]
Implemented and deployed to http://posc.meteor.com
