### ISSUE TITLE
Sorting outcome objective priorities

### ISSUE THREAD

**Issue by pgreenwo** [tableflip/posc#14]
The priority rows should be sortable.

## Background

As an objective setting tool, the POSC board is intended to allow users (leaders) to suggest and improve suggestions in answer to the question: "What should our organization do now?" 

The "outcome objective" is the one that, when complete, allows the intended outcome to measurably achieved. It is the objective card on the right of the priority row.  It seems likely that quite a bit of the debate during the objective setting process will be about the prioritization of outcome objectives so users will want to move the entire priority row, including the prerequisite objective cards, rather than just the cards in it.

They may also want to move an entire row to the trash (holding) area, in which case the other rows should move upwards so that the only priority rowgaps are at the bottom - you would start creating a new objective row at the bottom and then sort it to where you want it.)

The functionality is not in the JS Fiddle prototype.

**Comment by olizilla** [comment]
Implemented and deployed to http://posc.meteor.com
