### ISSUE TITLE
Date picker shows in Chrome but not Firefox

### ISSUE THREAD

**Issue by pgreenwo** [tableflip/posc#19]
A date picker has been implemented on the edit card dialog.  This shows up on Chrome, but not on Firefox

**Comment by olizilla** [comment]
The date picker is provided by the browser as the input type is set to `date`. We'll need a [polyfill](https://remysharp.com/2010/10/08/what-is-a-polyfill) for the browsers that don't support it.

**Comment by pgreenwo** [comment]
Not an issue for now then.
