### ISSUE TITLE
Prevent text overspill on objective cards

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#25]
![screen shot 2015-05-05 at 10 23 30](https://cloud.githubusercontent.com/assets/4499581/7469949/d00e6342-f310-11e4-8306-bd337640a893.jpg)

**Comment by pgreenwo** [comment]
This works OK, but I'd like 2 lines for the Title and One for the description as 1 line is too short...I think arrangement works fine with the mouse-over text.

**Comment by pgreenwo** [comment]
This works OK, but I'd like 2 lines for the Title and three for the description as 1 line is too short for the title, and the leader and the due date available in the mouse-over content.
