### ISSUE TITLE
Recently updated signal on card.

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#27]
#NEW!
![screen shot 2015-05-05 at 10 26 21](https://cloud.githubusercontent.com/assets/4499581/7470070/cf0cd82e-f311-11e4-9898-765c8cab381a.jpg)

OR

#updated!

![updated](https://cloud.githubusercontent.com/assets/4499581/7475070/562417a2-f33d-11e4-82a5-bdb77daf1c41.jpg)

**Comment by pgreenwo** [comment]
Takes up too much space and will complicate with text overflow issue.  Perhaps just embolden the outline of the Objective (card).
Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by pgreenwo** [comment]
@bmordan Didn't see the second image; this would work if the signal isn't too small. The signal is useful when people are collaborating on developing a POSC Map.

**Comment by pgreenwo** [comment]
Not sure why this fell-off being Iteration 2, so I've re-assigned it.

**Comment by pgreenwo** [comment]
OK, I like the way this works.
