### ISSUE TITLE
Sequence direction

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#32]
Indicate sequence direction (left to right is sequence, left most should be considered first) like this?

![poscdir](https://cloud.githubusercontent.com/assets/4499581/7470679/ee0f13ae-f316-11e4-9cbd-a6a128afb30e.jpg)

**Comment by pgreenwo** [comment]
Not sure what you’re showing me.  We need to include an “arrow of time” indicating that the sequence of activities is from left to right.

Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by bmordan** [comment]
More like this? Like the lable of an 'x axis' on a graph?

![screen shot 2015-05-05 at 16 11 25](https://cloud.githubusercontent.com/assets/4499581/7476092/52df62d0-f343-11e4-9f5c-ba3401018054.jpg)

**Comment by pgreenwo** [comment]
Change the word from “Time" to “Sequence” and that will do for now.
Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by liamwooding** [comment]
I was personally a bit confused by the sequence arrow and ended up with the wrong impression - here's a quick attempt at showing sequence by fading the objectives as they go from right to left, we could use some kind of colour gradient as well - what do you think @pgreenwo ?
![screen shot 2015-05-07 at 13 08 18](https://cloud.githubusercontent.com/assets/1327356/7514955/709ad778-f4ba-11e4-8c4e-9730ab983d68.png)

**Comment by pgreenwo** [comment]
A good suggestion - but unfortunately, to me, conveys the opposite message.

A POSC Map answers the question “What should I do next?” for a team of resources whose line-management is not necessarily aligned with the change objective. You read a POSC map like a book, top row, left to right, next row, left to right etc.

Perhaps putting a box at the top left of the POSC MAP, saying “Start Here ->”, like the one that says “Top priority” but at the left end of the Priority row.  
Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by liamwooding** [comment]
@pgreenwo ah, it seems I had the right idea from Bernard's picture then - I'd somehow got confused and thought the rightmost objective was top priority, the idea with the image was that the objectives become more faded the less urgent they are.

**Comment by pgreenwo** [comment]
@liamwooding The key insight of the POSC Map is that all the objectives in the top line have the same priority (top), but since some inevitably need to be done before the others there is a sequence in which they need to be addressed.  This is because it is really the intended outcome that dictates the priority...

**Comment by liamwooding** [comment]
@pgreenwo OK - we'll try a few different things and see what works.

**Comment by alanshaw** [comment]
Resolved in https://github.com/tableflip/posc/commit/3b322ab53cd1fd9be7fcbad68151920c5a4a4c56

**Comment by pgreenwo** [comment]
We've gone way off track. I was suggesting something like this (below), but now I can see the graphic, Bernard's first suggesting looks good.  Maybe we could combine them?

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/7540627/7564294/2f1e2b6c-f7dd-11e4-90b5-b71146626841.png)
