### ISSUE TITLE
Incorporate welcome video into introduction screen.

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#34]
Current home

![screen shot 2015-05-05 at 11 09 08](https://cloud.githubusercontent.com/assets/4499581/7470713/27f5ad94-f317-11e4-8562-e236654846c0.jpg)

**Comment by alanshaw** [comment]
@pgreenwo I'm guessing this is simply a youtube/vimeo video that needs embedding in the page?

**Comment by pgreenwo** [comment]
@alanshaw: For this and other pages of content, such as terms of use and contact details, I would prefer to be able to be in control of updates, so this can't just be fixed code.
