### ISSUE TITLE
Add terms of use, contact us page on website (PG to provide content).

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#35]

**Comment by alanshaw** [comment]
> From Philip:
> I think that this content should be controlled by me dynamically rather than hard-coded into the website.  How can we provide for that?  Can it be linked to specific pages or content from another site that I control?  This would allow me to update the video as I get better explaining things, and to update the terms of use as it becomes clear how the risks need to be mitigated.  Same idea for the contact us page.

**Comment by alanshaw** [comment]
@pgreenwo I suggest we build a really simple admin area with text areas where you can add in content for these pages.

For the contact us page, what had you envisaged? A simple block of text and an email address or something a little more elaborate with a form?

**Comment by pgreenwo** [comment]
@alanshaw I agree with your idea; this would also work for Issue 34.  For the contact page, for the moment, a simple block of text with an email address is fine.
