### ISSUE TITLE
Renaming terms for POSC

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#38]
Rename:
* card -> objective
* board -> map
* bucket -> scope

Actually, “card" and “board" are Tableflip originated terms and I’d like to move beyond them because they reinforce a paradigm about the tool that is wrong.  I think in terms of a POSC Map, Scope, Timeframe, Priorities, Sequence, Objectives and Outcomes. POSC stands for Prioritised Objective Setting and Communication.  A POSC Map has a Scope and a Timeframe. A row on the POSC Map is a sequence of objective that have to be achieved, with has a priority level.  The right hand objective typically describes a desired outcome, the left hand objective is the first in a sequence of objectives to achieve the right-hand - outcome - objective.  Why have I chosen these terms?  Because they seem to have about the right level of imprecision (or fuzziness, if you like).

**Comment by pgreenwo** [comment]
Please explain what a bucket is?  I’m not sure that scope is the right translation, as a POSC Map has a scope.

Is a bucket a priority level?

Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by alanshaw** [comment]
A bucket was a row of objectives, is now scope but can be called whatever you like.

**Comment by pgreenwo** [comment]
It’s a priority level, so call it a priority please.

Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>
